runtime: python39

GOOGLE_CLIENT_ID: %GOOGLE_CLIENT_ID%
GOOGLE_CLIENT_SECRET: %GOOGLE_CLIENT_SECRET%
UPLOAD_BUCKET: %UPLOAD_BUCKET%
PROJECT_ID: %PROJECT_ID%
SECOND_BUCKET: %SECOND_BUCKET%
handlers:

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
